### ISSUE TITLE
Videos are played slower than normal

### ISSUE THREAD

**Issue by stucki** [piccolo-dev/android_device_bq_piccolo#58]
When I'm playing a video through the speaker of the phone, the video is played slower than normal. A sequence of 1 minute takes 1:07 to play. You also here a clear difference because the tone pitch of the voices is much lower than normal.

However, when connect to my bluetooth headset and play the same sequence again, then the speed is normal, the problem is gone. It only happens when playing using the speaker of the phone.

I'm using Pocket Casts to watch the video, but I got feedback from another user that it also happens with other apps and the same video.

To try, I've used the latest video from this feed: http://www.srf.ch/podcasts/feeds/video/einstein.xml

(I'm using the cm-13.0-20160228 build from https://s.basketbuild.com/devs/eloimuns/bq/piccolo/)

**Comment by stucki** [comment]
I should also add that this used to work fine until some weeks ago.

**Comment by stucki** [comment]
Another user just reported that it works fine with a current version of cm-12.1. So it clearly seems to be an issue with cm-13.0.

**Comment by Kra1o5** [comment]
Hi @stucki ,

Im using X5 at the moment but @eloimuns can test it.

Greetings

**Comment by Kra1o5** [comment]
@stucki @eloimuns confirm it so I will find out the cause asap.

**Comment by stucki** [comment]
The issue still exists. Do you have any idea what could have caused it?

**Comment by Kra1o5** [comment]
Hi @stucki ,

Can you send me a logcat?

Thanks

**Comment by Kra1o5** [comment]
Hi @stucki ,

I merged some new changes from CAF, so you can test it in next build.

**Comment by stucki** [comment]
Thanks. I just tried with the 2016-04-17 build, but the problem still occurs. 30 seconds of video play in 35 seconds on the loudspeaker, but in correct speed via bluetooth...
